- name: Remove files of directories
  file:
    state: absent
    path: "{{item}}"
  with_items:
    - "{{zomboid_dir}}/Server"
    - "{{zomboid_dir}}/Saves/Multiplayer/{{zomboid_servername}}"

- name: Create Zomboid directory
  file:
    path: "{{zomboid_dir}}{{item}}"
    state: directory
  with_items:
    - '/' # root folder
    - "/Saves/Multiplayer/{{zomboid_servername}}"
    - '/Server'

- name: Copying pz server files
  ansible.builtin.copy:
    force: yes
    src: "{{ item }}"
    dest: "{{zomboid_dir}}/Server/{{ item | basename }}"
  with_fileglob:
    - "files/server/*"

- name: Copying pz save files
  ansible.builtin.copy:
    force: yes
    src: "saves/{{zomboid_servername}}.tar.gz"
    dest: "{{zomboid_dir}}/Saves/Multiplayer/{{zomboid_servername}}/{{zomboid_servername}}.tar.gz"

- name: Extract zomboid save file
  command: "tar -zxf {{zomboid_servername}}.tar.gz"
  args:
    chdir: "{{zomboid_dir}}/Saves/Multiplayer/{{zomboid_servername}}"

- name: Remove compacted save files
  file:
    path: "{{zomboid_dir}}/Saves/Multiplayer/{{zomboid_servername}}/{{zomboid_servername}}.tar.gz"
    state: absent
