- name: Insert/Update pzserver password
  become: yes
  become_method: su
  become_user: pzuser
  blockinfile:
    path: "{{zomboid_dir}}/Server/{{zomboid_servername}}.ini"
    block: "Password={{zomboid_server_password}}"
